name: ESP32 SSH Tunnel Library CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
    
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio
    
    - name: Download dependencies first
      run: |
        cd examples
        pio pkg install

    - name: Apply libssh2 configuration fix
      run: |
        cd examples
        chmod +x fix_libssh2_esp.sh
        ./fix_libssh2_esp.sh
    
    - name: Build for ESP32
      run: |
        cd examples
        pio run -e esp32dev
    
    - name: Verify no OS/400 files compiled
      run: |
        cd examples
        echo "=== Verification: OS/400 Files Check ==="
        if pio run -e esp32dev -v 2>&1 | grep -i "qtqiconv\|qadrt"; then
          echo "❌ ERROR: OS/400 platform files are being compiled!"
          exit 1
        else
          echo "✅ SUCCESS: No OS/400 platform files compiled"
        fi